### ISSUE TITLE
Possible to call Java from Rust?

### ISSUE THREAD

**Issue by brycefisher** [drrb/java-rust-example#1]
In all the (super awesome) examples in this repo, it seems that Java is invoking Rust functions.

Based on your experience with this repo, is it possible to use Rust-lang to create objects from Java classes and invoke Java methods on those objects?

**Comment by drrb** [comment]
Thanks for the comment! In case you're still looking at calling Java from Rust, you might be interested in:
https://github.com/bennettanderson/rjni
https://github.com/kud1ing/rucaja
